### ISSUE TITLE
Lien vers les polices cassés

### ISSUE THREAD

**Issue by GuillaumeHevin** [super-lou/INRAE_template#1]
Le nouveau lien pour télécharger les police : https://charte-identitaire.intranet.inrae.fr/valises-de-polices

**Comment by lou-heraut** [comment]
Merci ! 
N’hésites pas si tu vois d'autres problèmes dans ce template ou si tu as des propositions, je l'ai fais rapidement et utilisé qu'une seul fois donc je manque de recul
