### ISSUE TITLE
Compilateur XeLatex

### ISSUE THREAD

**Issue by GuillaumeHevin** [super-lou/INRAE_template#2]
Ce n'est pas un problème, mais ton document fonctionne en utilisant le compilateur XeLaTex que j'ai du téléchargé sur ma machine ici: 
https://doc.ubuntu-fr.org/xelatex

Je pense que le rajouter quelque part dans la doc à un endroit serait cool.

Une fois ça téléchargé ton template fonctionne très bien :) Merci encore :)

**Comment by lou-heraut** [comment]
oui bien-vu c'est à cause des polices que j'ai du faire ça je crois, merci ! je le précise

Je suis content que ça puisse t'être utile,
Bon LaTeX !
