### ISSUE TITLE
Probème compilation overleaf

### ISSUE THREAD

**Issue by beren2** [super-lou/INRAE_template#4]
Pour pouvoir compiler correctement le template avec overleaf, il faut ajouter "_\usepackage{raleway}_" dans le main.tex

**Comment by lou-heraut** [comment]
le template utilise une font pas libre de droit, Avenir, que vous pouvez normalement trouver [ici](https://charte-identitaire.intranet.inrae.fr/valises-de-polices) avec Raleway et normalement le template devrait compiler sans ce usepackage.

Mais oui par ouverture c'est souhaitable de rajouter une option de compilation sans cette police pas libre de droit. 
Merci
